<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-FG9S1KG" failures="1" tests="2" name="Error Validations Test" time="88.742" errors="0" timestamp="15 Dec 2024 05:15:14 GMT">
  <testcase classname="MyLearning.ErrorValidationsTest" name="LoginErrorValidation" time="1.547"/>
  <testcase classname="MyLearning.ErrorValidationsTest" name="ProductNameValidation" time="26.39">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at MyLearning.ErrorValidationsTest.ProductNameValidation(ErrorValidationsTest.java:39)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- ProductNameValidation -->
</testsuite> <!-- Error Validations Test -->
